FROM ghcr.io/graalvm/graalvm-ce:22.3.1 as graalvm

RUN gu install native-image

WORKDIR /usr/src/graalvmExample

RUN ls -l

#COPY src/*.java /usr/src/graalvmExample

RUN javac HelloWorld.java 

RUN native-image HelloWorld

RUN ls -la

#RUN  ./helloworld

# docker build . -t graalvm_example:v01 -f Dockerfile_graalvm
# docker run -it --rm --mount type=bind,source=/home/rafex/github/gist/dockers/graalvm/src,target=/usr/src/graalvmExample mount-ex

