FROM ghcr.io/graalvm/graalvm-ce:22.3.1 as build
RUN gu install native-image
WORKDIR /src
#RUN ls -l
COPY src/*.java /src
RUN javac HelloWorld.java
RUN native-image HelloWorld
RUN ls -lah
RUN  ./helloworld

#FROM scratch
#WORKDIR /src2
#COPY --from=build ./* .
#COPY --from=build helloworld /usr/bin/
#ENTRYPOINT ["/usr/bin/helloworld"]



